export const BALANCE = {
  // フィールド
  FIELD_WIDTH: 320,
  FIELD_HEIGHT: 568,

  // マナ
  INITIAL_MANA: 5.0,
  MAX_MANA: 10.0,
  MANA_REGEN_PER_SECOND: 0.6,
  OVERTIME_MANA_REGEN_PER_SECOND: 0.9,
  OVERTIME_THRESHOLD_SECONDS: 60,

  // バトル
  BATTLE_DURATION_SECONDS: 180,
  FPS: 60,
  DEPLOY_COOLDOWN_FRAMES: 180,
  DEPLOY_ZONE_MIN_Y: 350,

  // ユニット
  UNIT_RADIUS: 8,
  UNIT_DETECTION_RANGE_MULTIPLIER: 3,

  // 城
  PLAYER_CASTLE_HP: 500,
  CASTLE_DEFENSE: 3,
  CASTLE_WIDTH: 32,
  CASTLE_HEIGHT: 32,

  // パーティクル
  MAX_PARTICLES: 200,
  HIT_PARTICLE_LIFE: 15,
  DEATH_PARTICLE_LIFE: 30,
  CASTLE_HIT_PARTICLE_LIFE: 20,
  DEPLOY_PARTICLE_LIFE: 10,

  // ステータス範囲
  STATS: {
    HP: { min: 50, max: 200 },
    ATTACK: { min: 5, max: 30 },
    DEFENSE: { min: 1, max: 20 },
    SPEED: { min: 1.0, max: 4.0 },
    ATTACK_SPEED: { min: 15, max: 60 },
    RANGE: { min: 20, max: 80 },
    MANA_COST: { min: 2, max: 8 },
  },

  // 兵種相性ダメージ倍率
  TYPE_ADVANTAGE_MULTIPLIER: 1.3,

  // ヒーラー
  HEALER_HEAL_RATIO: 0.5,
  HEALER_DAMAGE_RATIO: 0.3,

  // 経済
  WIN_COINS: { min: 100, max: 200 },
  LOSS_COINS: 30,
  DAILY_CHALLENGE_WIN_COINS: 200,
  DAILY_CHALLENGE_LOSS_COINS: 50,
  UNIT_SLOT_COST: 500,
  DECK_SLOT_COST: 300,

  // 制限
  MAX_UNITS_IN_INVENTORY: 50,
  MAX_DECKS: 5,
  MAX_ADS_PER_DAY: 5,
  UNIT_NAME_MAX_LENGTH: 8,
  PLAYER_NAME_MAX_LENGTH: 8,

  // リプレイ
  REPLAY_SAMPLE_INTERVAL: 12,
  REPLAY_GIF_FPS: 10,
  REPLAY_GIF_DURATION_SECONDS: 10,
  REPLAY_GIF_SIZE: 320,

  // 広告
  INTERSTITIAL_MIN_INTERVAL_SECONDS: 90,
  INTERSTITIAL_SHOW_EVERY_N_LOSSES: 3,
} as const;
